### PR TITLE
Add 'username' as database field and index to filter

### PR DESCRIPTION
**Pull request by bap14**
Refs #2 

This provides the ability to write the username to a new column, indexes that column and exposes a new query parameter to optionally filter by specific username.

### CODE REVIEW

**Comment by mccxiv** [comment]
So this doesn't update the schema of the existing db, is that right? I would need to delete the current database file to get the new column

**Comment by bap14** [comment]
It does not update it, so new schema would need to be initialized.  I'm not sure if or how you currently handle schema updates, so I figured I'd leave that out for now.  Do you have a mechanism like migrations or something to handle this?

**Comment by joshleaver** [comment]
you could always just add it manually to the database

**Comment by mccxiv** [comment]
Thanks, I want to tweak it to alter the table before I release this though. I'd prefer not doing it manually

**Pull request merged**
